services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - "6379:6379"

#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#       - redis
#     env_file:
#       - .env
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_db
#       SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#       SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#       SPRING_REDIS_HOST: redis
#       SPRING_REDIS_PORT: 6379
#       POSTGRES_HOST: postgres

volumes:
  postgres_data: